source("./R files/jd3_init.R")
source("./R files/jd3_fractionalairline.R")
source("./R files/jd3_x11.R")
source("./R files/jd3_stl.R")
source("./R files/jd3_holidays.R")

casualties<-read.csv("./Data/Daily casualties/dailycasualtiesGB.csv")
c<-casualties[,2]
plot(c, type='l')

jhol<-jd3_holidays()
add(jhol, c(12,31))
add(jhol, "NewYear")
add(jhol, "NewYear", offset=+1)
add(jhol, "Christmas", offset=-1)
add(jhol, "Christmas")
add(jhol, "Christmas", offset=+1)
add(jhol, "Easter", offset=-2)
add(jhol, "Easter", offset=-1)
add(jhol, "EasterMonday")
add(jhol, "Easter", offset=+2)
add(jhol, "MayDay")
add(jhol, "Ascension")
add(jhol, "WhitMonday")
add(jhol, "Assumption")
add(jhol, "AllSaintsDay")
add(jhol, c(5,8))
add(jhol, c(11,11))

hol<-jd3_holidaysMatrix(jhol, "2005-01-01", length = length(c), type = "Default")
d<-jd3_periodicAirline(c, x=hol, periods=c(7, 365.25), outliers=c("ao", "ls", "wo"), criticalValue = 6)
c<-result(d, "lin")

spec.ar(c, order=30)
q1<-jd3_fractionalAirlineDecomposition(c, 7,sn=T)
w<-result(q1, "s")
wsa<-result(q1, "n")
spec.ar(wsa, order=30)
q2<-jd3_fractionalAirlineDecomposition(wsa, 365.25,sn=T)
a<-result(q2, "s")
sa<-result(q2, "n")
spec.ar(sa, order=30)

x1<-jd3_x11(c, 7, multiplicative = F, trendLength = 13, seas1 = "S3X15")
w1<-result(x1, "d10")
w1sa<-result(x1, "d11")
spec.ar(w1sa, order=30)
x2<-jd3_x11(w1sa, 365.25, multiplicative = F, trendLength = 367, seas1 = "S3X5")
a1<-result(x2, "d10")
sa1<-result(x2, "d11")
spec.ar(sa1, order=30)

plot(w[1:140], type="l")
lines(w1[1:140], col="red")
plot(a[1:750], type="l")
lines(a1[1:750], col="red")
