if(!require(rJava)){
  install.packages("rJava")
}
library("rJava")
.jinit()
.jaddClassPath("./Java/demetra-datatypes-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-eco-datatypes-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-core-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-stats-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-eco-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-ssf-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-arima-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-ts-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-benchmarking-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-benchmarking-datatypes-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-sts-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-sts-datatypes-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-sacore-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-stl-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-x11-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./Java/demetra-r-1.0.0-SNAPSHOT.jar")

jd_clobj<-.jcall("java/lang/Class", "Ljava/lang/Class;", "forName", "java.lang.Object")
