source("./R files/jd3_init.R")
source("./R files/jd3_fractionalairline.R")
source("./R files/jd3_x11.R")
source("./R files/jd3_stl.R")
source("./R files/jd3_holidays.R")

cic<-read.table("./Data/cic.txt")
y<-log(cic[,2])

jhol<-jd3_holidays()
add(jhol, "NewYear")
add(jhol, "MayDay")
add(jhol, "AllSaintsDay")
add(jhol, "Christmas", offset=-3)
add(jhol, "Christmas", offset=-2)
add(jhol, "Christmas", offset=-1)
add(jhol, "Christmas")
add(jhol, "Christmas", offset=+1)
add(jhol, "Christmas", offset=+2)
add(jhol, "Easter", offset=-3)
add(jhol, "Easter", offset=-2)
add(jhol, "Easter", offset=-1)
add(jhol, "Easter")
add(jhol, "EasterMonday")
add(jhol, "Easter", offset=+2)
add(jhol, "Ascension")
add(jhol, "WhitMonday")

hol<-jd3_holidaysMatrix(jhol, "2002-12-31", length = length(y))
d<-jd3_periodicAirline(y, x=hol, periods=c(7, 365.25/12, 365.25), outliers=c("ao", "ls", "wo"), criticalValue = 6)

print(result(d,"parameters"))
print(result(d,"outliers"))
print(result(d, "b"))
print(result(d, "t"))
y<-result(d, "lin")

c<-jd3_fractionalAirlineDecomposition(y, period=7, TRUE)
c1<-jd3_fractionalAirlineDecomposition(result(c,"sa"), period=365.25/12, adjust = FALSE)
c2<-jd3_fractionalAirlineDecomposition(result(c1,"sa"), period=365.25, adjust = FALSE)
# The final decomposition is given by
w<-result(c,"s")
m<-result(c1,"s")
t<-result(c2,"t")
sa<-result(c2,"sa")
s<-result(c2,"s")
i<-result(c2,"i")
seatsdecomp<-cbind(y,t,sa,w,m,s,i)

y<-exp(y)
# sa of daily series with X11
a<-jd3_x11(y, period=7, multiplicative = TRUE, seas0="S3X15", seas1="S3X15", trendLength = 9)
a1<-jd3_x11(result(a,"d11"), period=365.25/12, multiplicative = TRUE, seas0="S3X15", seas1="S3X15", trendLength = 65)
a2<-jd3_x11(result(a1,"d11"), period=365.25, multiplicative = TRUE, trendLength = 367)

# The final decomposition is given by
w<-result(a,"d10")
m<-result(a1,"d10")
t<-result(a2,"d12")
sa<-result(a2,"d11")
s<-result(a2,"d10")
i<-result(a2,"d13")
x11decomp<-cbind(y,t,sa,w,m, s,i)

plot(x11decomp[1:733, "s"], type="l")
lines(exp(seatsdecomp[1:733, "s"]), col="red")

plot(x11decomp[1:70, "w"], type="l")
lines(exp(seatsdecomp[1:70, "w"]), col="red")

plot(x11decomp[1:155, "m"], type="l")
lines(exp(seatsdecomp[1:155, "m"]), col="red")
